import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_name': 'Resume Maker',
      'splash_loading': 'Loading...',
      'dashboard': 'Dashboard',
      'create_resume': 'Create Resume',
      'settings': 'Settings',
      'about': 'About',
      'version': 'Version',
      'full_name': 'Full Name',
      'contact': 'Contact',
      'address': 'Address',
      'linkedin': 'LinkedIn',
      'website': 'Website',
      'description': 'Description',
      'education': 'Education',
      'add_education': 'Add Education',
      'institution': 'Institution',
      'degree': 'Degree',
      'field_of_study': 'Field of Study',
      'start_date': 'Start Date',
      'end_date': 'End Date',
      'grade': 'Grade',
      'experience': 'Experience',
      'add_experience': 'Add Experience',
      'company': 'Company',
      'position': 'Position',
      'currently_working': 'Currently Working',
      'skills': 'Skills',
      'add_skill': 'Add Skill',
      'skill_name': 'Skill Name',
      'skill_level': 'Skill Level',
      'certificates': 'Certificates',
      'add_certificate': 'Add Certificate',
      'certificate_name': 'Certificate Name',
      'issuer': 'Issuer',
      'date': 'Date',
      'credential_id': 'Credential ID',
      'save': 'Save',
      'create_pdf': 'Create PDF',
      'preview_pdf': 'Preview PDF',
      'select_template': 'Select Template',
      'template_classic': 'Classic',
      'template_modern': 'Modern',
      'template_minimal': 'Minimal',
      'font_size': 'Font Size',
      'language': 'Language',
      'dark_mode': 'Dark Mode',
      'english': 'English',
      'hindi': 'Hindi',
      'telugu': 'Telugu',
      'no_resumes': 'No resumes yet. Create your first resume!',
      'delete': 'Delete',
      'edit': 'Edit',
      'view': 'View',
      'cancel': 'Cancel',
      'confirm': 'Confirm',
      'delete_resume': 'Delete Resume',
      'delete_confirmation': 'Are you sure you want to delete this resume?',
      'resume_saved': 'Resume saved successfully',
      'pdf_created': 'PDF created successfully',
      'error': 'Error',
      'fill_required_fields': 'Please fill all required fields',
      'remove': 'Remove',
      'email': 'Email',
      'attachment': 'Attachment (Optional)',
      'fresher': 'I am a Fresher',
      'select_color': 'Select Color',
      'template_basic': 'Basic',
      'description_limit': 'Description must be 100 characters or less',
      'email_required': 'Email is required',
      'linkedin_required': 'LinkedIn is required',
      'education_required': 'At least one education entry is required',
      'experience_required':
          'At least one experience entry is required (unless fresher)',
      'skills_required': 'At least one skill is required',
    },
    'hi': {
      'app_name': 'रिज्यूमे मेकर',
      'splash_loading': 'लोड हो रहा है...',
      'dashboard': 'डैशबोर्ड',
      'create_resume': 'रिज्यूमे बनाएं',
      'settings': 'सेटिंग्स',
      'about': 'के बारे में',
      'version': 'संस्करण',
      'full_name': 'पूरा नाम',
      'contact': 'संपर्क',
      'address': 'पता',
      'linkedin': 'लिंक्डइन',
      'website': 'वेबसाइट',
      'description': 'विवरण',
      'education': 'शिक्षा',
      'add_education': 'शिक्षा जोड़ें',
      'institution': 'संस्थान',
      'degree': 'डिग्री',
      'field_of_study': 'अध्ययन का क्षेत्र',
      'start_date': 'आरंभ तिथि',
      'end_date': 'समाप्ति तिथि',
      'grade': 'ग्रेड',
      'experience': 'अनुभव',
      'add_experience': 'अनुभव जोड़ें',
      'company': 'कंपनी',
      'position': 'पद',
      'currently_working': 'वर्तमान में काम कर रहे हैं',
      'skills': 'कौशल',
      'add_skill': 'कौशल जोड़ें',
      'skill_name': 'कौशल का नाम',
      'skill_level': 'कौशल स्तर',
      'certificates': 'प्रमाणपत्र',
      'add_certificate': 'प्रमाणपत्र जोड़ें',
      'certificate_name': 'प्रमाणपत्र का नाम',
      'issuer': 'जारीकर्ता',
      'date': 'तारीख',
      'credential_id': 'क्रेडेंशियल आईडी',
      'save': 'सहेजें',
      'create_pdf': 'पीडीएफ बनाएं',
      'select_template': 'टेम्पलेट चुनें',
      'template_classic': 'क्लासिक',
      'template_modern': 'आधुनिक',
      'template_minimal': 'न्यूनतम',
      'font_size': 'फ़ॉन्ट आकार',
      'language': 'भाषा',
      'dark_mode': 'डार्क मोड',
      'english': 'अंग्रेज़ी',
      'hindi': 'हिंदी',
      'telugu': 'तेलुगु',
      'no_resumes': 'अभी तक कोई रिज्यूमे नहीं। अपना पहला रिज्यूमे बनाएं!',
      'delete': 'हटाएं',
      'edit': 'संपादित करें',
      'view': 'देखें',
      'cancel': 'रद्द करें',
      'confirm': 'पुष्टि करें',
      'delete_resume': 'रिज्यूमे हटाएं',
      'delete_confirmation': 'क्या आप वाकई इस रिज्यूमे को हटाना चाहते हैं?',
      'resume_saved': 'रिज्यूमे सफलतापूर्वक सहेजा गया',
      'pdf_created': 'पीडीएफ सफलतापूर्वक बनाया गया',
      'error': 'त्रुटि',
      'fill_required_fields': 'कृपया सभी आवश्यक फ़ील्ड भरें',
      'remove': 'हटाएं',
    },
    'te': {
      'app_name': 'రెజ్యూమ్ మేకర్',
      'splash_loading': 'లోడ్ అవుతోంది...',
      'dashboard': 'డాష్‌బోర్డ్',
      'create_resume': 'రెజ్యూమ్ సృష్టించండి',
      'settings': 'సెట్టింగ్‌లు',
      'about': 'గురించి',
      'version': 'వెర్షన్',
      'full_name': 'పూర్తి పేరు',
      'contact': 'సంప్రదింపు',
      'address': 'చిరునామా',
      'linkedin': 'లింక్డ్‌ఇన్',
      'website': 'వెబ్‌సైట్',
      'description': 'వివరణ',
      'education': 'విద్య',
      'add_education': 'విద్యను జోడించండి',
      'institution': 'సంస్థ',
      'degree': 'డిగ్రీ',
      'field_of_study': 'అధ్యయన రంగం',
      'start_date': 'ప్రారంభ తేదీ',
      'end_date': 'ముగింపు తేదీ',
      'grade': 'గ్రేడ్',
      'experience': 'అనుభవం',
      'add_experience': 'అనుభవాన్ని జోడించండి',
      'company': 'కంపెనీ',
      'position': 'స్థానం',
      'currently_working': 'ప్రస్తుతం పని చేస్తున్నారు',
      'skills': 'నైపుణ్యాలు',
      'add_skill': 'నైపుణ్యాన్ని జోడించండి',
      'skill_name': 'నైపుణ్య పేరు',
      'skill_level': 'నైపుణ్య స్థాయి',
      'certificates': 'సర్టిఫికెట్లు',
      'add_certificate': 'సర్టిఫికెట్ జోడించండి',
      'certificate_name': 'సర్టిఫికెట్ పేరు',
      'issuer': 'జారీచేసేవారు',
      'date': 'తేదీ',
      'credential_id': 'క్రెడెన్షియల్ ID',
      'save': 'సేవ్ చేయండి',
      'create_pdf': 'PDF సృష్టించండి',
      'select_template': 'టెంప్లేట్ ఎంచుకోండి',
      'template_classic': 'క్లాసిక్',
      'template_modern': 'ఆధునిక',
      'template_minimal': 'కనిష్ట',
      'font_size': 'ఫాంట్ పరిమాణం',
      'language': 'భాష',
      'dark_mode': 'డార్క్ మోడ్',
      'english': 'ఇంగ్లీష్',
      'hindi': 'హిందీ',
      'telugu': 'తెలుగు',
      'no_resumes': 'ఇంకా రెజ్యూమ్‌లు లేవు. మీ మొదటి రెజ్యూమ్‌ను సృష్టించండి!',
      'delete': 'తొలగించు',
      'edit': 'సవరించు',
      'view': 'చూడండి',
      'cancel': 'రద్దు చేయండి',
      'confirm': 'నిర్ధారించండి',
      'delete_resume': 'రెజ్యూమ్ తొలగించు',
      'delete_confirmation':
          'మీరు ఖచ్చితంగా ఈ రెజ్యూమ్‌ను తొలగించాలనుకుంటున్నారా?',
      'resume_saved': 'రెజ్యూమ్ విజయవంతంగా సేవ్ చేయబడింది',
      'pdf_created': 'PDF విజయవంతంగా సృష్టించబడింది',
      'error': 'లోపం',
      'fill_required_fields': 'దయచేసి అన్ని అవసరమైన ఫీల్డ్‌లను పూరించండి',
      'remove': 'తొలగించు',
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      ['en', 'hi', 'te'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
